india/urls.py
from django.urls import path 
from india.views import *
app_name='india'

urlpatterns=[
    path('kohli/',kohli,name='kohli'),
    path('kohli_bat/',kohli_bat,name='kohli_bal'),
]

pak/urls.py
from django.urls import path 
from pak.views import  *
app_name='pak'

urlpatterns=[
    path('babar/',babar,name='babar'),
    path('babar_bat/',babar_bat,name='babar_bat'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
from ipl.views import *
import india,pak
urlpatterns = [
    path('admin/', admin.site.urls),
    path('sachin/',sachin,name='sachin'),
    path('india/',include('india.urls')),
    path('pak/',include('pak.urls')),
    path('sachin_bat/',sachin_bat,name='sachin_bat'),
]

india/models.py
from django.db import models

# Create your models here.

ipl/models.py
from django.db import models

# Create your models here.

pak/models.py
from django.db import models

# Create your models here.

india/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def kohli(request):
    return render(request,'kohli.html')

def kohli_bat(request):
    return HttpResponse('Kohli is the father of Pakistan')

ipl/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def sachin(request):
    return render(request,'sachin.html')

def sachin_bat(request):
    return HttpResponse('god of the cricket')

pak/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def babar(request):
    return render(request,'babar.html')

def babar_bat(request):
    return HttpResponse('babar is a good player')

templates/babar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>here babar is the father of the pakistan</h1>
        <h1><a href="{% url 'india:kohli' %}">go to the kohli page</a></h1>
        <h1><a href="{% url 'sachin' %}"> go to the sachin sir page</a></h1>
    </center>
</body>
</html>

templates/kohli.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>here kohli is the father of the pakistan</h1>
        <h1><a href="{% url 'pak:babar' %}">go to the babar page</a></h1>
        <h1><a href="{% url 'sachin' %}"> go to the sachin sir page</a></h1>
    </center>
</body>
</html>

templates/sachin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>here kohli is the father of the pakistan</h1>
        <h1><a href="{% url 'pak:babar' %}">go to the babar page</a></h1>
        <h1><a href="{% url 'india:kohli' %}"> go to the kohli page</a></h1>
    </center>
</body>
</html>